kafka:
  bootstrap-servers: kafka-1:9092
  schema-registry: http://schema-registry:8081

spring:
  application:
    name: streams-app

processor:
  retweet-count:
    app-id: retweet-counter
    enabled: true
    input-topic: tweets
    output-topic: retweet-count
  yourkey:
    input-topic:
    output-topic: